name: Tests
on:
  push:

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore Nix Store
        id: restore-nix-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            /home/runner/nix
          key: ${{ runner.os }}-${{ hashFiles('./flake.lock') }}

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            # save space on disk and in cache
            # auto-optimise-store = true
            store = /home/runner/nix
            # keep all store paths necessary to build the outputs
            keep-outputs = true
            keep-derivations = true

      - name: Run Tests
        run: |
          nix develop . -c bash -c "go test . -v -race"

      - name: Save nix store
        uses: actions/cache/save@v3
        if: ${{ steps.restore-nix-cache.outputs.cache-hit == false }}
        with:
          key: ${{ runner.os }}-${{ hashFiles('./flake.lock') }}
          path: |
            /home/runner/nix
